### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by wanghuok** [dengdan/seglink#25]
Hi. I want to test the pretrained model on my image. when i run'./scripts/test.sh 0 model/model.ckpt-217867 /home/wh/work/jyh_dataset/testimage', i get this error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

os: ubuntu 16.04
python:2.7
opencv:3.3.0
tensorflow-gpu 1.4.0

**Comment by wanghuok** [comment]
Whole error message:
./scripts/test.sh 0 model/model.ckpt-217867 /home/wh/work/jyh_dataset/test
++ set -e
++ export CUDA_VISIBLE_DEVICES=0
++ CUDA_VISIBLE_DEVICES=0
++ CHECKPOINT_PATH=model/model.ckpt-217867
++ DATASET_DIR=/home/wh/work/jyh_dataset/test
++ python test_seglink.py --checkpoint_path=model/model.ckpt-217867 --gpu_memory_fraction=-1 --seg_conf_threshold=0.8 --link_conf_threshold=0.5 --dataset_dir=/home/wh/work/jyh_dataset/test
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file tf_logging.py, line 82

**Comment by garybruckheimer** [comment]
Have the same error wanghuok..do you find a solution?

**Comment by Jeep-Z** [comment]
@wanghuok @garybruckheimer I got the same problem. Do you guys figure it out?

**Comment by soumyadip1997** [comment]
Just look at the solution in #22 . It states the error is minor and wont stop the algo from running
